# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35c3855e43fdf357f9c10e84a1ab3ea2d913a75e0fb0978a44851736e4bd9f0b4449a62504d15644ec567a75beeee4a61d89f2a8a7244a85b26c8747364dca64

test:
  secret_key_base: 25c64c147c1980c1fb5f9b3b9c06770cc1b4751d7a63c9de601f035fe2eb0b822cdde7161f6fe1a5d00b0c17da2554eb36938842bc32397dca5f64a08387a2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
#secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: 35c3855e43fdf357f9c10e84a1ab3ea2d913a75e0fb0978a44851736e4bd9f0b4449a62504d15644ec567a75beeee4a61d89f2a8a7244a85b26c8747364dca64
  
